name: mosque_ease
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.9
  sqflite: ^2.3.0
  path: ^1.8.3
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.1
  http: ^1.1.0
  intl: ^0.18.1
  pdf: ^3.10.7
  path_provider: ^2.1.5
  open_file: ^3.3.2
  url_launcher: ^6.2.4
  fl_chart: ^0.66.2
  linked_scroll_controller: ^0.2.0
  google_mobile_ads: ^4.0.0
  permission_handler: ^12.0.0+1
  flutter_compass: ^0.8.1
  geolocator: ^14.0.0
  share_plus: ^11.0.0
  cross_file: ^0.3.4+2
  file_picker: ^10.1.2
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ScheherazadeNew
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
        - asset: assets/fonts/ScheherazadeNew-Bold.ttf
          weight: 700
    - family: Indopak
      fonts:
        - asset: assets/fonts/indopak.ttf
    - family: NotoNastaliqUrdu
      fonts:
        - asset: assets/fonts/static/NotoNastaliqUrdu-Regular.ttf
        - asset: assets/fonts/static/NotoNastaliqUrdu-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/NotoNastaliqUrdu-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/NotoNastaliqUrdu-Bold.ttf
          weight: 700
    - family: JameelNooriNastaleeqKasheeda
      fonts:
        - asset: assets/fonts/Jameel Noori Nastaleeq Kasheeda/Jameel Noori Nastaleeq Kasheeda.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/quran.sqlite

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logoo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_logoo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_logoo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/app_logoo.png"
